### ISSUE TITLE
Update image architecture to support NAS Synology run docker

### ISSUE THREAD

**Issue by dhhiep** [dhhiep/fshare_tool#7]
```bash
Unable to find image 'hoanghiepitvnn/fshare_tool:latest' locally
latest: Pulling from hoanghiepitvnn/fshare_tool
Digest: sha256:39b3b1d248fa2400fe1061ec5d5954cd562654e44e6d137be28f8419bd801905
Status: Image is up to date for hoanghiepitvnn/fshare_tool:latest
WARNING: image with reference hoanghiepitvnn/fshare_tool was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8
docker: Error response from daemon: image with reference hoanghiepitvnn/fshare_tool:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64/v8.
See 'docker run --help'.
```

Example docker compose worked on NAS Synology
```yaml
version: "3.9"
services:
  kodi-mariadb:
    image: linuxserver/mariadb
    container_name: kodi-mariadb
    environment:
      - PUID=100
      - PGID=1026
      - MYSQL_ROOT_PASSWORD=xxx
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped

  emulatorjs:
    image: [lscr.io/linuxserver/emulatorjs:latest](http://lscr.io/linuxserver/emulatorjs:latest)
    container_name: emulatorjs
    network_mode: bridge
    
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    healthcheck:
     test: curl -f http://localhost:3000/ || exit 1
    environment:
      - PUID=911
      - PGID=911
      - TZ=Asia/Ho_Chi_Minh
      - SUBFOLDER=/ #optional
    volumes:
      - /volume1/docker/emulatorjs/config:/config:rw
      - /volume1/docker/emulatorjs/data:/data:rw
    ports:
      - 3000:3000
      - 80:80
      - 4001:4001 #optional
    restart: unless-stopped
```
